application: gdgmendoza
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

#- url: /controllers
#  static_dir: controllers

#- url: /modules
#  static_dir: modules

- url: /components
  static_dir: components

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /js/vendor
  static_dir: js/vendor

- url: /views
  static_dir: views

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /robots\.txt
  static_files: robots.txt
  upload: robots.txt

#- url: /
#  static_files: index.html
#  upload: index.html

# Endpoints handler
- url: /_ah/spi/.*
  script: cloud.application

- url: .*
  script: gdgmendoza.app